insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Mame', 'Normant', '218 Maywood Place', null, 'Lebanon', '(312) 7600255', 'mnormant0@pinterest.com', 2024);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Ignacio', 'Skones', '51859 Michigan Avenue', null, 'China', '(174) 7223585', 'iskones1@xinhuanet.com', 2021);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Melisande', 'Mebs', '1625 Grayhawk Circle', null, 'Indonesia', '(291) 6955119', 'mmebs2@liveinternet.ru', 2019);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Albertina', 'Minchi', '3 Blackbird Center', 'Pennsylvania', 'United States', '(814) 8734408', 'aminchi3@eventbrite.com', 2021);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Zaccaria', 'Royste', '81 Loomis Avenue', null, 'Nigeria', '(958) 2161483', 'zroyste4@ebay.co.uk', 2021);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Deck', 'Farlamb', '99 Farragut Hill', null, 'China', '(714) 1950110', 'dfarlamb5@blogspot.com', 2024);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Hans', 'Vasnetsov', '8891 Victoria Hill', null, 'Latvia', '(362) 7497387', 'hvasnetsov6@house.gov', 2021);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Kym', 'Plumbley', '339 Union Street', null, 'South Korea', '(167) 4372947', 'kplumbley7@soup.io', 2024);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Ellery', 'Challenger', '4 Sachtjen Point', null, 'Czech Republic', '(683) 1358011', 'echallenger8@gnu.org', 2024);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Merle', 'Teodori', '39715 Portage Alley', null, 'Laos', '(937) 5665386', 'mteodori9@indiatimes.com', 2022);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Josephine', 'Beaten', '6 Clove Junction', null, 'China', '(774) 9291899', 'jbeatena@hexun.com', 2021);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Shanie', 'Ewles', '848 Trailsway Center', null, 'China', '(221) 7456907', 'sewlesb@php.net', 2020);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Franciskus', 'McIlvaney', '7 Pepper Wood Street', null, 'Peru', '(388) 1148595', 'fmcilvaneyc@example.com', 2020);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Aurelea', 'Travis', '39922 Meadow Valley Street', null, 'Brazil', '(707) 1356220', 'atravisd@printfriendly.com', 2020);
insert into StudentDatabase.Students (FirstName, LastName, Address1, City, Country, PhoneNumber, EmailAddress, GraduationYear) values ('Francesco', 'Elkins', '93372 Division Plaza', null, 'Honduras', '(886) 3441101', 'felkinse@fema.gov', 2020);

insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Engineering', '5/6/2020', '11/26/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Product Management', '4/5/2020', '12/4/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Product Management', '8/21/2020', '3/7/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Services', '8/20/2020', '8/20/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Product Management', '1/18/2020', '7/28/2021');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Marketing', '2/15/2020', '10/18/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Product Management', '8/23/2020', '3/5/2021');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Marketing', '7/7/2020', '4/14/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Training', '1/21/2020', '9/1/2021');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Research and Development', '2/21/2020', '6/7/2021');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Services', '10/9/2020', '1/24/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Engineering', '2/11/2020', '7/7/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Training', '7/26/2020', '11/23/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Training', '9/4/2020', '3/18/2022');
insert into StudentDatabase.COURSE (CourseName, CourseStart, CourseEnd) values ('Research and Development', '9/4/2020', '11/28/2022');

insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (40, 6, 30);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (25, 7, 18);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (35, 5, 20);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (12, 12, 40);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (11, 4, 43);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (40, 13, 21);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (56, 9, 49);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (43, 12, 42);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (7, 14, 54);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (55, 2, 28);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (48, 14, 5);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (52, 14, 15);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (59, 7, 6);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (51, 10, 4);
insert into StudentDatabase.Student_Course (Attendance, Project, FinalExam) values (55, 15, 9);

insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$4613.85', '$656.68', 'americanexpress', '9/29/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$901.00', '$3466.28', 'mastercard', '12/20/2019');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$4588.72', '$3961.78', 'laser', '7/10/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$2279.53', '$3397.80', 'diners-club-enroute', '4/8/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$670.85', '$3031.17', 'maestro', '10/19/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$1091.12', '$1264.90', 'visa-electron', '6/21/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$3851.09', '$3948.55', 'visa-electron', '10/28/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$873.92', '$1991.50', 'bankcard', '10/14/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$2839.80', '$4471.57', 'jcb', '8/18/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$4510.62', '$3917.47', 'maestro', '3/3/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$4938.86', '$1308.78', 'mastercard', '10/5/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$1618.08', '$3973.16', 'jcb', '12/16/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$4860.24', '$2316.39', 'diners-club-us-ca', '3/9/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$282.98', '$4345.20', 'jcb', '7/25/2020');
insert into StudentDatabase.Payment (AmountDue, AmountPaid, PaymentType, PaymentDate) values ('$1036.47', '$3843.57', 'jcb', '6/20/2020');

insert into StudentDatabase.Scholarship (Description1, Amount) values ('Stanton-Denesik', '$1049.02');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Swaniawski-Stracke', '$1258.53');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Williamson-Blanda', '$1850.46');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Dooley-Stracke', '$2969.73');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Metz-Kerluke', '$1986.44');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Dooley-Gaylord', '$2430.61');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Quitzon and Sons', '$1407.70');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Paucek LLC', '$600.54');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Runolfsdottir, Durgan and Keeling', '$2795.55');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Bayer, Wolff and Cormier', '$1036.97');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Grady, Mosciski and Wiza', '$1602.52');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('King and Sons', '$989.06');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Hoppe-Weissnat', '$1805.62');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Weber, Gleichner and Corwin', '$2238.50');
insert into StudentDatabase.Scholarship (Description1, Amount) values ('Nienow-Reichert', '$1090.68');

